### ISSUE TITLE
Issue with Seeing New Changes in Dev Environment

### ISSUE THREAD

**Issue by aeolingamenfel** [GoogleChromeLabs/ProgressiveWordPress#16]
Hello, I ran into a couple issues with the service worker/routing code that I'm trying to debug (may open an issue later if this turns out to be something not specific to my environment/setup), but whenever I try to modify the code (mostly adding some debugging `console.log` statements for now, or tweaking logic), I cannot see the changes appear. 

I have tried:
  - Restarting the docker instances generated when I first set up using `docker-compose up -d` / `docker-compose down`
  - Clearing the app cache (Chrome dev tools > Application tab > Clear Storage section > check all boxes > click "Clear site data"
  - Rebuilding using either `node build.js` or `npm run build` before each step above

With no effect on the output, rendered HTML, etc. So, any guidance on what I might be doing wrong would be extremely appreciated. 

My tweaks were to `sw.js`, `header.php`, and `router.js`, if that helps at all. I can provide a complete list of changes I was working on if that would help, as well.

---

Edit: My environment, which could be useful:
macOS v10.13.2 running Docker 17.09.1-ce-mac42 (21090)
Browser: Chrome Version 63.0.3239.84
Node: v8.1.2
NPM: v.5.6.0

**Comment by surma** [comment]
I haven’t dug deep on why this is, but checking “Disable Cache” in DevTool’s Network panel is usually all it takes to see updates. I think I am caching `sw.php` in my ServiceWorker but haven’t fixed that yet.
