### ISSUE TITLE
How can I install this on my wordpress blog running on CPanel?

### ISSUE THREAD

**Issue by MKDan** [GoogleChromeLabs/ProgressiveWordPress#23]
I uploaded and extracted this .zip file on the /wp-content/themes/ folder,

On the theme installation page, it says "

Name | Description |  
ProgressiveWordPress-master | Stylesheet is missing.

**Comment by surma** [comment]
This repository isn’t a straight-up theme. You have to build it. Take a look at the README.

That being said, this theme is probably not ready for production or even generic enough to be re-used. Prepare to be disappointed.
