### ISSUE TITLE
No peer certificate available - Bad SSL Response

### ISSUE THREAD

**Issue by tedmasterweb** [GoogleChromeLabs/ProgressiveWordPress#5]
Hi,

Following the instructions to simply download and run locally (`docker pull…; docker-compose up -d`) and the server is responding with ERR_SSL_PROTOCOL_ERROR when accessing https://localhost:8080.

Not sure if this is helpful, but perhaps…
```
openssl s_client -connect localhost:8080
WARNING: can't open config file: /Users/mattt/Desktop/PostgresApp/Postgres/Vendor/postgres/ssl/openssl.cnf
CONNECTED(00000003)
140735691084808:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:s23_clnt.c:766:
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 7 bytes and written 322 bytes
---
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
---
```
Would love to get rid of the `WARNING: can't open config file:` but not sure where that's really coming from, a botched Postgres SQL installation, I think, that I'm no longer using, but that doesn't make much sense either because it is outside the Docker container.

Any help greatly appreciated.

Thanks in advance.

Running on Mac OS X 10.12.6 (16G29)

**Comment by surma** [comment]
Ah my bad! I removed TLS from localhost a while ago but apparently didn’t update the README. Navigating to `http://localhost:8080` should work just fine. I’ll update the README,

**Comment by surma** [comment]
See [new instructions](https://github.com/GoogleChromeLabs/ProgressiveWordPress#docker) :)
